# Generated by Django 5.2.10 on 2026-01-28 20:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("products", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Cart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "session_key",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=40,
                        null=True,
                        verbose_name="Session Key",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="TND", max_length=3, verbose_name="Currency"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="carts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cart",
                "verbose_name_plural": "Carts",
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "order_number",
                    models.CharField(
                        db_index=True,
                        max_length=50,
                        unique=True,
                        verbose_name="Order Number",
                    ),
                ),
                ("email", models.EmailField(max_length=254, verbose_name="Email")),
                ("phone", models.CharField(max_length=20, verbose_name="Phone")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Payment"),
                            ("paid", "Paid"),
                            ("processing", "Processing"),
                            ("shipped", "Shipped"),
                            ("delivered", "Delivered"),
                            ("cancelled", "Cancelled"),
                            ("refunded", "Refunded"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="TND", max_length=3, verbose_name="Currency"
                    ),
                ),
                (
                    "subtotal",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Subtotal"
                    ),
                ),
                (
                    "discount_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Discount Amount",
                    ),
                ),
                (
                    "shipping_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Shipping Cost",
                    ),
                ),
                (
                    "tax_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Tax Amount",
                    ),
                ),
                (
                    "total",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Total"
                    ),
                ),
                (
                    "total_impact_items",
                    models.IntegerField(default=0, verbose_name="Total Impact Items"),
                ),
                (
                    "impact_summary",
                    models.JSONField(
                        default=dict,
                        help_text="Breakdown of impact by item type",
                        verbose_name="Impact Summary",
                    ),
                ),
                (
                    "shipping_first_name",
                    models.CharField(max_length=100, verbose_name="First Name"),
                ),
                (
                    "shipping_last_name",
                    models.CharField(max_length=100, verbose_name="Last Name"),
                ),
                (
                    "shipping_company",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Company"
                    ),
                ),
                (
                    "shipping_address_1",
                    models.CharField(max_length=200, verbose_name="Address Line 1"),
                ),
                (
                    "shipping_address_2",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Address Line 2"
                    ),
                ),
                (
                    "shipping_city",
                    models.CharField(max_length=100, verbose_name="City"),
                ),
                (
                    "shipping_state",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="State/Province"
                    ),
                ),
                (
                    "shipping_postal_code",
                    models.CharField(max_length=20, verbose_name="Postal Code"),
                ),
                (
                    "shipping_country",
                    models.CharField(
                        default="TN", max_length=2, verbose_name="Country"
                    ),
                ),
                (
                    "billing_same_as_shipping",
                    models.BooleanField(
                        default=True, verbose_name="Billing Same as Shipping"
                    ),
                ),
                (
                    "billing_first_name",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Billing First Name"
                    ),
                ),
                (
                    "billing_last_name",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Billing Last Name"
                    ),
                ),
                (
                    "billing_company",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Billing Company"
                    ),
                ),
                (
                    "billing_address_1",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        verbose_name="Billing Address Line 1",
                    ),
                ),
                (
                    "billing_address_2",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        verbose_name="Billing Address Line 2",
                    ),
                ),
                (
                    "billing_city",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Billing City"
                    ),
                ),
                (
                    "billing_state",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        verbose_name="Billing State/Province",
                    ),
                ),
                (
                    "billing_postal_code",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Billing Postal Code"
                    ),
                ),
                (
                    "billing_country",
                    models.CharField(
                        blank=True, max_length=2, verbose_name="Billing Country"
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("stripe", "Stripe (Card)"),
                            ("bank_transfer", "Bank Transfer"),
                            ("cash_on_delivery", "Cash on Delivery"),
                        ],
                        default="stripe",
                        max_length=50,
                        verbose_name="Payment Method",
                    ),
                ),
                (
                    "payment_id",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Payment ID"
                    ),
                ),
                (
                    "paid_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Paid At"),
                ),
                (
                    "shipping_method",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Shipping Method"
                    ),
                ),
                (
                    "tracking_number",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Tracking Number"
                    ),
                ),
                (
                    "shipped_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Shipped At"
                    ),
                ),
                (
                    "delivered_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Delivered At"
                    ),
                ),
                (
                    "customer_notes",
                    models.TextField(blank=True, verbose_name="Customer Notes"),
                ),
                (
                    "admin_notes",
                    models.TextField(blank=True, verbose_name="Admin Notes"),
                ),
                (
                    "coupon_code",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Coupon Code"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="orders",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Order",
                "verbose_name_plural": "Orders",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ImpactEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Title")),
                (
                    "title_en",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Title (English)"
                    ),
                ),
                ("description", models.TextField(verbose_name="Description")),
                (
                    "description_en",
                    models.TextField(blank=True, verbose_name="Description (English)"),
                ),
                ("school", models.CharField(max_length=200, verbose_name="School")),
                ("date", models.DateField(verbose_name="Date")),
                (
                    "items_delivered",
                    models.IntegerField(verbose_name="Items Delivered"),
                ),
                (
                    "item_type",
                    models.CharField(max_length=100, verbose_name="Item Type"),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True, null=True, upload_to="impact/", verbose_name="Photo"
                    ),
                ),
                ("video_url", models.URLField(blank=True, verbose_name="Video URL")),
                (
                    "is_published",
                    models.BooleanField(default=True, verbose_name="Published"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "funded_by_orders",
                    models.ManyToManyField(
                        blank=True,
                        related_name="impact_events",
                        to="orders.order",
                        verbose_name="Funded By Orders",
                    ),
                ),
            ],
            options={
                "verbose_name": "Impact Event",
                "verbose_name_plural": "Impact Events",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "product_name",
                    models.CharField(max_length=200, verbose_name="Product Name"),
                ),
                (
                    "product_sku",
                    models.CharField(max_length=50, verbose_name="Product SKU"),
                ),
                ("quantity", models.PositiveIntegerField(verbose_name="Quantity")),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Unit Price"
                    ),
                ),
                (
                    "subtotal",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Subtotal"
                    ),
                ),
                (
                    "impact_quantity",
                    models.IntegerField(verbose_name="Impact Quantity"),
                ),
                (
                    "impact_item",
                    models.CharField(max_length=100, verbose_name="Impact Item"),
                ),
                (
                    "impact_school",
                    models.CharField(max_length=200, verbose_name="Impact School"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="orders.order",
                        verbose_name="Order",
                    ),
                ),
                (
                    "producer",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="products.producer",
                        verbose_name="Producer",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="products.product",
                        verbose_name="Product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Order Item",
                "verbose_name_plural": "Order Items",
            },
        ),
        migrations.CreateModel(
            name="CartItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(default=1, verbose_name="Quantity"),
                ),
                (
                    "box_items",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of product IDs in composable box",
                        verbose_name="Box Items",
                    ),
                ),
                (
                    "added_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Added At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "cart",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="orders.cart",
                        verbose_name="Cart",
                    ),
                ),
                (
                    "composable_box",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="products.composablebox",
                        verbose_name="Composable Box",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="products.product",
                        verbose_name="Product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cart Item",
                "verbose_name_plural": "Cart Items",
                "unique_together": {("cart", "product", "composable_box")},
            },
        ),
    ]
