# Generated by Django 5.2.10 on 2026-01-28 20:45

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Producer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Name")),
                (
                    "slug",
                    models.SlugField(blank=True, unique=True, verbose_name="Slug"),
                ),
                ("bio", models.TextField(blank=True, verbose_name="Biography")),
                (
                    "bio_en",
                    models.TextField(blank=True, verbose_name="Biography (English)"),
                ),
                (
                    "bio_ar",
                    models.TextField(blank=True, verbose_name="Biography (Arabic)"),
                ),
                ("location", models.CharField(max_length=200, verbose_name="Location")),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="producers/",
                        verbose_name="Photo",
                    ),
                ),
                (
                    "total_products_sold",
                    models.IntegerField(default=0, verbose_name="Total Products Sold"),
                ),
                (
                    "total_earnings",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Total Earnings",
                    ),
                ),
                (
                    "member_since",
                    models.DateField(auto_now_add=True, verbose_name="Member Since"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
            ],
            options={
                "verbose_name": "Producer",
                "verbose_name_plural": "Producers",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Name")),
                (
                    "name_en",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Name (English)"
                    ),
                ),
                (
                    "name_ar",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Name (Arabic)"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(blank=True, unique=True, verbose_name="Slug"),
                ),
                (
                    "sku",
                    models.CharField(max_length=50, unique=True, verbose_name="SKU"),
                ),
                ("description", models.TextField(verbose_name="Description")),
                (
                    "description_en",
                    models.TextField(blank=True, verbose_name="Description (English)"),
                ),
                (
                    "description_ar",
                    models.TextField(blank=True, verbose_name="Description (Arabic)"),
                ),
                (
                    "short_description",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="Short Description"
                    ),
                ),
                (
                    "ingredients",
                    models.TextField(
                        blank=True,
                        help_text="Ce qu'il y a dans mon produit",
                        verbose_name="Ingredients",
                    ),
                ),
                (
                    "ingredients_en",
                    models.TextField(blank=True, verbose_name="Ingredients (English)"),
                ),
                (
                    "usage",
                    models.TextField(
                        blank=True,
                        help_text="Utilisation",
                        verbose_name="Usage Instructions",
                    ),
                ),
                (
                    "usage_en",
                    models.TextField(
                        blank=True, verbose_name="Usage Instructions (English)"
                    ),
                ),
                (
                    "unit_type",
                    models.CharField(
                        choices=[
                            ("individual", "Individual Item"),
                            ("box", "Pre-made Box"),
                            ("composable", "Composable Box Item"),
                        ],
                        default="individual",
                        max_length=20,
                        verbose_name="Unit Type",
                    ),
                ),
                (
                    "price_tnd",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Price (TND)",
                    ),
                ),
                (
                    "price_eur",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Price (EUR)",
                    ),
                ),
                (
                    "compare_at_price_tnd",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Original price for showing discount",
                        max_digits=10,
                        null=True,
                        verbose_name="Compare at Price (TND)",
                    ),
                ),
                (
                    "b2b_min_quantity",
                    models.IntegerField(
                        default=10, verbose_name="B2B Minimum Quantity"
                    ),
                ),
                (
                    "b2b_price_tnd",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="B2B Price (TND)",
                    ),
                ),
                (
                    "b2b_price_eur",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="B2B Price (EUR)",
                    ),
                ),
                (
                    "is_natural",
                    models.BooleanField(default=False, verbose_name="100% Natural"),
                ),
                (
                    "is_organic",
                    models.BooleanField(default=False, verbose_name="Organic/Bio"),
                ),
                (
                    "is_handmade",
                    models.BooleanField(default=False, verbose_name="Handmade"),
                ),
                ("is_vegan", models.BooleanField(default=False, verbose_name="Vegan")),
                (
                    "is_cruelty_free",
                    models.BooleanField(default=False, verbose_name="Cruelty Free"),
                ),
                (
                    "impact_description",
                    models.CharField(
                        help_text='e.g., "6 barres energetiques peuvent etre fournies a des enfants de Sidi Mechreg"',
                        max_length=500,
                        verbose_name="Impact Description",
                    ),
                ),
                (
                    "impact_description_en",
                    models.CharField(
                        blank=True,
                        max_length=500,
                        verbose_name="Impact Description (English)",
                    ),
                ),
                (
                    "impact_description_ar",
                    models.CharField(
                        blank=True,
                        max_length=500,
                        verbose_name="Impact Description (Arabic)",
                    ),
                ),
                (
                    "impact_school",
                    models.CharField(
                        help_text='e.g., "Sidi Mechreg"',
                        max_length=200,
                        verbose_name="Impact School",
                    ),
                ),
                (
                    "impact_quantity",
                    models.IntegerField(
                        help_text="e.g., 6 (number of items provided per purchase)",
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Impact Quantity",
                    ),
                ),
                (
                    "impact_item",
                    models.CharField(
                        help_text='e.g., "barres energetiques"',
                        max_length=100,
                        verbose_name="Impact Item",
                    ),
                ),
                (
                    "impact_item_en",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Impact Item (English)"
                    ),
                ),
                (
                    "stock_quantity",
                    models.IntegerField(default=0, verbose_name="Stock Quantity"),
                ),
                (
                    "track_inventory",
                    models.BooleanField(default=True, verbose_name="Track Inventory"),
                ),
                (
                    "low_stock_threshold",
                    models.IntegerField(default=10, verbose_name="Low Stock Threshold"),
                ),
                (
                    "allow_backorder",
                    models.BooleanField(default=False, verbose_name="Allow Backorder"),
                ),
                (
                    "weight",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Weight (g)",
                    ),
                ),
                (
                    "dimensions",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Dimensions"
                    ),
                ),
                (
                    "meta_title",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Meta Title"
                    ),
                ),
                (
                    "meta_description",
                    models.TextField(blank=True, verbose_name="Meta Description"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                (
                    "is_featured",
                    models.BooleanField(default=False, verbose_name="Featured"),
                ),
                (
                    "average_rating",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=3,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="Average Rating",
                    ),
                ),
                (
                    "review_count",
                    models.IntegerField(default=0, verbose_name="Review Count"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "producer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="products",
                        to="products.producer",
                        verbose_name="Producer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product",
                "verbose_name_plural": "Products",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ComposableBox",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Name")),
                (
                    "name_en",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Name (English)"
                    ),
                ),
                ("slug", models.SlugField(unique=True, verbose_name="Slug")),
                ("description", models.TextField(verbose_name="Description")),
                (
                    "description_en",
                    models.TextField(blank=True, verbose_name="Description (English)"),
                ),
                ("image", models.ImageField(upload_to="boxes/", verbose_name="Image")),
                (
                    "min_items",
                    models.IntegerField(default=3, verbose_name="Minimum Items"),
                ),
                (
                    "max_items",
                    models.IntegerField(default=10, verbose_name="Maximum Items"),
                ),
                (
                    "price_tnd",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Base price for the box (items may add extra cost)",
                        max_digits=10,
                        verbose_name="Base Price (TND)",
                    ),
                ),
                (
                    "price_eur",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Base Price (EUR)",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "eligible_products",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Products that can be added to this box type",
                        related_name="eligible_for_boxes",
                        to="products.product",
                        verbose_name="Eligible Products",
                    ),
                ),
            ],
            options={
                "verbose_name": "Composable Box",
                "verbose_name_plural": "Composable Boxes",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ProductCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Name")),
                (
                    "name_en",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Name (English)"
                    ),
                ),
                (
                    "name_ar",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Name (Arabic)"
                    ),
                ),
                ("slug", models.SlugField(unique=True, verbose_name="Slug")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "description_en",
                    models.TextField(blank=True, verbose_name="Description (English)"),
                ),
                (
                    "description_ar",
                    models.TextField(blank=True, verbose_name="Description (Arabic)"),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        help_text="Emoji or icon class",
                        max_length=50,
                        verbose_name="Icon",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="categories/",
                        verbose_name="Image",
                    ),
                ),
                ("order", models.IntegerField(default=0, verbose_name="Display Order")),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                (
                    "show_in_menu",
                    models.BooleanField(default=True, verbose_name="Show in Menu"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="products.productcategory",
                        verbose_name="Parent Category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product Category",
                "verbose_name_plural": "Product Categories",
                "ordering": ["order", "name"],
            },
        ),
        migrations.AddField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                to="products.productcategory",
                verbose_name="Category",
            ),
        ),
        migrations.CreateModel(
            name="ProductImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(upload_to="products/", verbose_name="Image"),
                ),
                (
                    "alt_text",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Alt Text"
                    ),
                ),
                (
                    "is_primary",
                    models.BooleanField(default=False, verbose_name="Primary Image"),
                ),
                ("order", models.IntegerField(default=0, verbose_name="Display Order")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="products.product",
                        verbose_name="Product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product Image",
                "verbose_name_plural": "Product Images",
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rating",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="Rating",
                    ),
                ),
                (
                    "title",
                    models.CharField(blank=True, max_length=200, verbose_name="Title"),
                ),
                ("comment", models.TextField(verbose_name="Comment")),
                (
                    "is_verified_purchase",
                    models.BooleanField(
                        default=False, verbose_name="Verified Purchase"
                    ),
                ),
                (
                    "is_approved",
                    models.BooleanField(default=True, verbose_name="Approved"),
                ),
                (
                    "helpful_votes",
                    models.IntegerField(default=0, verbose_name="Helpful Votes"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="products.product",
                        verbose_name="Product",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Review",
                "verbose_name_plural": "Reviews",
                "ordering": ["-created_at"],
                "unique_together": {("product", "user")},
            },
        ),
    ]
