# Generated by Django 5.2.10 on 2026-01-28 20:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("products", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "customer_type",
                    models.CharField(
                        choices=[
                            ("individual", "Individual Customer (B2C)"),
                            ("company", "Company (B2B)"),
                        ],
                        default="individual",
                        max_length=20,
                        verbose_name="Customer Type",
                    ),
                ),
                (
                    "phone",
                    models.CharField(blank=True, max_length=20, verbose_name="Phone"),
                ),
                (
                    "date_of_birth",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date of Birth"
                    ),
                ),
                (
                    "company_name",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Company Name"
                    ),
                ),
                (
                    "company_tax_id",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Company Tax ID"
                    ),
                ),
                (
                    "company_address",
                    models.TextField(blank=True, verbose_name="Company Address"),
                ),
                (
                    "company_contact_name",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Contact Person"
                    ),
                ),
                (
                    "default_shipping_address_1",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Address Line 1"
                    ),
                ),
                (
                    "default_shipping_address_2",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Address Line 2"
                    ),
                ),
                (
                    "default_shipping_city",
                    models.CharField(blank=True, max_length=100, verbose_name="City"),
                ),
                (
                    "default_shipping_state",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="State/Province"
                    ),
                ),
                (
                    "default_shipping_postal_code",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Postal Code"
                    ),
                ),
                (
                    "default_shipping_country",
                    models.CharField(
                        default="TN", max_length=2, verbose_name="Country"
                    ),
                ),
                (
                    "total_purchases",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Total Purchases",
                    ),
                ),
                (
                    "total_orders",
                    models.IntegerField(default=0, verbose_name="Total Orders"),
                ),
                (
                    "total_impact_items",
                    models.IntegerField(
                        default=0,
                        help_text="Total items donated through purchases (e.g., energy bars)",
                        verbose_name="Total Impact Items",
                    ),
                ),
                (
                    "impact_breakdown",
                    models.JSONField(
                        default=dict,
                        help_text="Breakdown of impact by item type",
                        verbose_name="Impact Breakdown",
                    ),
                ),
                (
                    "preferred_currency",
                    models.CharField(
                        choices=[("TND", "Tunisian Dinar"), ("EUR", "Euro")],
                        default="TND",
                        max_length=3,
                        verbose_name="Preferred Currency",
                    ),
                ),
                (
                    "preferred_language",
                    models.CharField(
                        choices=[("fr", "French"), ("en", "English"), ("ar", "Arabic")],
                        default="fr",
                        max_length=5,
                        verbose_name="Preferred Language",
                    ),
                ),
                (
                    "newsletter_subscribed",
                    models.BooleanField(
                        default=False, verbose_name="Newsletter Subscribed"
                    ),
                ),
                (
                    "accepts_marketing",
                    models.BooleanField(
                        default=False, verbose_name="Accepts Marketing"
                    ),
                ),
                (
                    "email_verified",
                    models.BooleanField(default=False, verbose_name="Email Verified"),
                ),
                (
                    "phone_verified",
                    models.BooleanField(default=False, verbose_name="Phone Verified"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="customer",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Customer",
                "verbose_name_plural": "Customers",
            },
        ),
        migrations.CreateModel(
            name="CustomerAddress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "address_type",
                    models.CharField(
                        choices=[
                            ("shipping", "Shipping"),
                            ("billing", "Billing"),
                            ("both", "Both"),
                        ],
                        default="both",
                        max_length=10,
                        verbose_name="Address Type",
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(default=False, verbose_name="Default Address"),
                ),
                (
                    "first_name",
                    models.CharField(max_length=100, verbose_name="First Name"),
                ),
                (
                    "last_name",
                    models.CharField(max_length=100, verbose_name="Last Name"),
                ),
                (
                    "company",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Company"
                    ),
                ),
                (
                    "address_1",
                    models.CharField(max_length=200, verbose_name="Address Line 1"),
                ),
                (
                    "address_2",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Address Line 2"
                    ),
                ),
                ("city", models.CharField(max_length=100, verbose_name="City")),
                (
                    "state",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="State/Province"
                    ),
                ),
                (
                    "postal_code",
                    models.CharField(max_length=20, verbose_name="Postal Code"),
                ),
                (
                    "country",
                    models.CharField(
                        default="TN", max_length=2, verbose_name="Country"
                    ),
                ),
                (
                    "phone",
                    models.CharField(blank=True, max_length=20, verbose_name="Phone"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="addresses",
                        to="customers.customer",
                        verbose_name="Customer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Customer Address",
                "verbose_name_plural": "Customer Addresses",
            },
        ),
        migrations.CreateModel(
            name="Wishlist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "added_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Added At"),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wishlists",
                        to="customers.customer",
                        verbose_name="Customer",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wishlisted_by",
                        to="products.product",
                        verbose_name="Product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Wishlist Item",
                "verbose_name_plural": "Wishlist Items",
                "unique_together": {("customer", "product")},
            },
        ),
    ]
