# Generated by Django 5.2.10 on 2026-03-22 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='b2b_status',
            field=models.CharField(choices=[('not_applicable', 'Not Applicable'), ('pending_approval', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='not_applicable', max_length=20, verbose_name='B2B Status'),
        ),
    ]
