# Generated by Django 5.2.10 on 2026-03-22 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_add_b2b_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='default_shipping_first_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='First Name'),
        ),
        migrations.AddField(
            model_name='customer',
            name='default_shipping_last_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Last Name'),
        ),
    ]
