# Generated by Django 5.2.10 on 2026-03-21 20:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name (FR)')),
                ('name_en', models.CharField(blank=True, max_length=100, verbose_name='Name (EN)')),
                ('name_ar', models.CharField(blank=True, max_length=100, verbose_name='Name (AR)')),
                ('slug', models.SlugField(unique=True)),
                ('flag_emoji', models.CharField(default='🌍', max_length=10, verbose_name='Flag Emoji')),
                ('description', models.TextField(blank=True, verbose_name='Description (FR)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('order', models.IntegerField(default=0, verbose_name='Display Order')),
            ],
            options={
                'verbose_name': 'Country',
                'verbose_name_plural': 'Countries',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DonationProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title (FR)')),
                ('title_en', models.CharField(blank=True, max_length=200, verbose_name='Title (EN)')),
                ('description', models.TextField(blank=True, verbose_name='Description (FR)')),
                ('description_en', models.TextField(blank=True, verbose_name='Description (EN)')),
                ('school', models.CharField(blank=True, max_length=200, verbose_name='School / Beneficiary')),
                ('category', models.CharField(choices=[('food', 'Alimentation'), ('infrastructure', 'Infrastructure'), ('sports', 'Sport'), ('education', 'Éducation'), ('health', 'Santé'), ('other', 'Autre')], default='other', max_length=30, verbose_name='Category')),
                ('goal_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Goal Amount')),
                ('currency', models.CharField(default='TND', max_length=3, verbose_name='Currency')),
                ('image', models.ImageField(blank=True, null=True, upload_to='donation_projects/', verbose_name='Image')),
                ('deadline', models.DateField(blank=True, null=True, verbose_name='Deadline')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Featured')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='donations.country')),
            ],
            options={
                'verbose_name': 'Donation Project',
                'verbose_name_plural': 'Donation Projects',
                'ordering': ['-is_featured', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donor_name', models.CharField(blank=True, max_length=200, verbose_name='Donor Name')),
                ('donor_email', models.EmailField(blank=True, max_length=254, verbose_name='Donor Email')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Amount')),
                ('currency', models.CharField(default='TND', max_length=3, verbose_name='Currency')),
                ('payment_method', models.CharField(choices=[('stripe', 'Carte bancaire (Stripe)'), ('bank_transfer', 'Virement bancaire')], default='stripe', max_length=20, verbose_name='Payment Method')),
                ('payment_id', models.CharField(blank=True, max_length=200, verbose_name='Payment ID')),
                ('message', models.TextField(blank=True, verbose_name='Message')),
                ('is_anonymous', models.BooleanField(default=False, verbose_name='Anonymous')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('completed', 'Complété'), ('failed', 'Échoué')], default='pending', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donations', to='donations.donationproject')),
            ],
            options={
                'verbose_name': 'Donation',
                'verbose_name_plural': 'Donations',
                'ordering': ['-created_at'],
            },
        ),
    ]
