# Generated by Django 5.2.10 on 2026-03-22 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='donation_countries/', verbose_name='Image'),
        ),
    ]
